export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  PRODUCTS: {
    BASE: '/products',
    GET_ALL: '/products',
    GET_BY_ID: (id: string) => `/products/${id}`,
    CREATE: '/products',
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    UPDATE_STOCK: (id: string) => `/products/${id}/stock`,
  },
  CREDITS: {
    BASE: '/credit-client',
    GET_ALL: '/credit-client',
    GET_BY_CLIENT: (clientId: string) => `/credit-client/${clientId}`,
    GET_TRANSACTIONS: (clientId: string) => `/credit-client/${clientId}/transactions`,
    GET_SUMMARY: '/credit-client/summary',
    CREATE: '/credit-client',
    UPDATE: (id: string) => `/credit-client/${id}`,
  },
  INVOICES: {
    BASE: '/invoices',
    GET_ALL: '/invoices',
    GET_BY_ID: (id: string) => `/invoices/${id}`,
    CREATE: '/invoices',
    UPDATE: (id: string) => `/invoices/${id}`,
    DELETE: (id: string) => `/invoices/${id}`,
    GENERATE_PDF: (id: string) => `/invoices/${id}/pdf`,
    MARK_PAID: (id: string) => `/invoices/${id}/paid`,
    CANCEL: (id: string) => `/invoices/${id}/cancel`,
  },
  WALLET: {
    BASE: '/wallet',
    GET_BALANCE: '/wallet/balance',
    GET_TRANSACTIONS: '/wallet/transactions',
    DEPOSIT: '/wallet/deposit',
    WITHDRAW: '/wallet/withdraw',
  },
  DASHBOARD: {
    BASE: '/dashboard',
    GET_STATS: '/dashboard/stats',
    GET_RECENT_ACTIVITY: '/dashboard/recent-activity',
    GET_CHART_DATA: '/dashboard/chart-data',
  },
  USERS: {
    BASE: '/users',
    GET_PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
    CHANGE_PASSWORD: '/users/change-password',
  },
  UPLOAD: {
    BASE: '/upload',
    UPLOAD_FILE: '/upload',
    UPLOAD_MULTIPLE: '/upload/multiple',
    GET_FILE: (filename: string) => `/uploads/${filename}`,
  },
};